# Generated by Django 5.2 on 2025-05-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("My_App", "0002_alter_room_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="deleted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
