# Generated by Django 5.2 on 2025-05-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("My_App", "0003_alter_booking_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="deleted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
